function init(self)
	msg.post(".", "acquire_input_focus")
end


function on_input(self, action_id, action)
	if gui.is_enabled(gui.get_node("background")) then
		if action_id == hash("touch") and action.pressed then -- <2>
			if gui.pick_node(gui.get_node("button"), action.x, action.y) then -- <5>
				msg.post("/mode_select#mode_select", "enable")
				msg.post("#", "disable")
			end
		end
	end
end
